### ISSUE TITLE
What's the difference between rawEvaluate() and evaluate() in AI class?

### ISSUE THREAD

**Issue by nkg114mc** [dhblooo/Rapfi-gomocup#1]
Hi Haobin,

Thanks for sharing the code of your engine. The code is well written and is very inspiring!

This is not an issue, but just a general question about a detail of the code for my personal curiosity. I see you have two evaluation functions, one is `rawEvaluate()`, and the other is `evaluate()`. I understand that rawEvaluate is the incremental-maintained sum of values of four-shape-combinations for all Empty positions across the board. I see evaluate() has an additional statement than rawEvaluate():

`value = (value - rawStaticEval[ply - 1]) / 2;`

This is pretty confusing for me. Why the evaluation value needs to interact with the rawEvaluate() of the last ply? What's the theory behind such a computation?

Thanks in advance!

**Comment by dhbloo** [comment]
Oops.. I didn't notice this issue until now. Sorry for the late reply. 
For the question, this is a simple trick to smooth the evaluation between odd and even ply. Since normally the player with one more stone on board will be given a higher score, causing evaluation fluctuates greatly between plys, leading to un-intuitive search results(this problem can be obversed in another open source ai Carbon). 
By taking the average of evaluation from both odd and even ply, the problem is solved, and this modification have little impact on playing strength. Another possible solution is to add a const offset for the player with less stone(something like a contempt in chess engine) , but my test results shows they are not better than the above method.

**Comment by yllgl** [comment]
@nkg114mc @dhbloo 
Do you understand the code? I don't understand what some variables means. Could you give me some advice?
```C++
enum Pattern : UInt8 {
	DEAD, 
	B1,   F1,
	B2J0, B2J2, 
	F2J0, F2J1, F2J2,         
	B3J0, B3J1, B3J2,
	F3J0, F3J1,
	B4,   F4,
	F5
};
class Evaluator {
private:
	static Pattern PATTERN[256][256];  // 65536 = 256 * 256 = 4 ^ 8//what is this?
	static PatternCode PCODE[16][16][16][16];  // 65536 = 16 ^ 4//what is this?
        static Pattern4 PATTERN4[3876];//what is this?

protected:
	static short Score[3876];
	static short Value[3876];

	struct Cell {
		UInt8 key[4][2]; //what is this?
		Pattern pattern[2][4];
		short score[2];
		short eval[2];
		Pattern4 pattern4[2];
		UInt8 cand;//what is this?
		bool isLose;
        }
}
```

What does Pattern `B3J2` mean? Does it mean o●●xx●o pattern where x means empty? And `F2J2` means ●xx●?
what does `PCODE[16][16][16][16]` mean? Why is it four dimensions? How does the magic value of 3876  come from?
What `key[4][2]` in struct Cell mean? And what does `cand` in Cell struct mean?
